### ISSUE TITLE
tuple index out of range

### ISSUE THREAD

**Issue by wangbq18** [renjunxiang/lic2019_ie#1]
您好，按照说明运行代码时报错， /XXX/XXX/net/module/Features.py line 57 in forward batch_first=True  IndexError:tuple index out of range

**Comment by renjunxiang** [comment]
我刚才从头运行了一遍，没有问题。我猜是你输入数据的时候没有按照长度从大到小排序，或者是pytorch版本问题

**Comment by wangbq18** [comment]
> 我刚才从头运行了一遍，没有问题。我猜是你输入数据的时候没有按照长度从大到小排序，或者是pytorch版本问题

数据还要排序吗，请问你用的是哪个版本

**Comment by renjunxiang** [comment]
我在dataset里面已经排序了，这个错误我记得是没排序会报的。1.0.0和1.0.1应该都可以

**Comment by wangbq18** [comment]
谢谢！

**Comment by renjunxiang** [comment]
最近同事也发现了这个问题，不用我的预处理结果就没问题，建议预处理清空重新运行。
